name: 'database_universe_project'
description: 'Database Universe package for help you save any data in anywhere with high performance speed, easy feature and ready for scala business'
version: '0.0.18'
homepage: 'https://youtube.com/@azkadev'
repository: 'https://github.com/General-Developer/database_universe'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://youtube.com/@azkadev'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
environment:
  sdk: '>=3.6.0 <4.0.0'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependencies:
  general_lib: '^0.0.68'
  packagex: '^1.0.0'
  path: '^1.9.0'
  yaml: '^3.1.3'
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
project:
  type: ''
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
